sys_includes = ["sys/types.h", "stdint.h"]
include_guard = "_RELIBC_GRP_H"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true

[export]
include = ["group"]
