/* automatically generated by rust-bindgen */
#[repr(C)]
#[derive(Debug, Copy)]
pub struct group {
    pub gr_name: *mut libc::c_char,
    pub gr_passwd: *mut libc::c_char,
    pub gr_gid: gid_t,
    pub gr_mem: *mut *mut libc::c_char,
}
impl Clone for group {
    fn clone(&self) -> Self {
        *self
    }
}
#[no_mangle]
pub extern "C" fn getgrgid(gid: gid_t) -> *mut group {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn getgrnam(name: *const libc::c_char) -> *mut group {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn getgrgid_r(
    gid: gid_t,
    grp: *mut group,
    buffer: *mut libc::c_char,
    bufsize: usize,
    result: *mut *mut group,
) -> libc::c_int {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn getgrnam_r(
    name: *const libc::c_char,
    grp: *mut group,
    buffer: *mut libc::c_char,
    bufsize: usize,
    result: *mut *mut group,
) -> libc::c_int {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn getgrent() -> *mut group {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn endgrent() {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn setgrent() {
    unimplemented!();
}
