# Makefile
# Makefile for Relibc
#
# This makefile handles the building of the C library (relibc), the dynamic linker (ld.so),
# and the tests. It supports building mainly for Redox and Linux.

TOML := Cargo.toml
CONFIG := .config
BUILD := build
SRC := src

# CARGO_BUILD_DIR: The directory where cargo puts its output (default: "target")
CARGO_BUILD_DIR := target

# CROSS_TARGET: The variable defining the compilation target architecture.
# If left empty, cargo compiles for the host architecture.
CROSS_TARGET ?=

# Detect the target architecture and OS
CARGO_FLAGS :=
ifneq ($(CROSS_TARGET),)
	CARGO_FLAGS += --target $(CROSS_TARGET)
endif

# Default target is release
PROFILE := release
ifeq ($(PROFILE),release)
	CARGO_FLAGS += --release
endif

# Compiler settings
AR ?= ar
CC ?= gcc
LD ?= ld
NM ?= nm
OBJCOPY ?= objcopy
RANLIB ?= ranlib
STRIP ?= strip

# Retrieve the internal include path for the compiler (GCC/Clang).
CC_INTERNAL_INCS := $(shell $(CC) -print-file-name=include)
CC_INTERNAL_INCS_FIXED := $(shell $(CC) -print-file-name=include-fixed)

# Construct the flags. We only add the directory if it exists.
# We intentionally DO NOT include /usr/include here.
CC_NOSTDINC_FLAGS := -nostdinc -I$(CC_INTERNAL_INCS)
ifneq ($(wildcard $(CC_INTERNAL_INCS_FIXED)),)
    CC_NOSTDINC_FLAGS += -I$(CC_INTERNAL_INCS_FIXED)
endif

# Flags for C compilation (used for openlibm and tests)
CFLAGS ?= -O2 -g -Wall -Wextra -fPIC
CPPFLAGS ?=

.PHONY: all clean install install-headers install-libs list-headers test libs headers

# Default target
all: libs $(BUILD)/crt0.o

# Target specifically for building libraries
libs: $(BUILD)/libc.a $(BUILD)/libc.so

$(BUILD)/include:
	mkdir -p $@

$(BUILD)/openlibm: openlibm
	rm -rf $@
	cp -r $< $@

# 1. Build Rust Lib (librelibc.a) FIRST.
# This step runs build.rs, which generates the missing headers (like assert.h) into $(CARGO_BUILD_DIR)/include.
$(BUILD)/librelibc.a: Cargo.toml src/* src/*/* src/*/*/*
	mkdir -p $(BUILD)
	cargo rustc $(CARGO_FLAGS) -- -C soft-float -C code-model=kernel --emit link=$@

# 2. Prepare Headers
# We gather headers from the source `include/` AND the `target/include` generated by step 1.
headers: $(BUILD)/librelibc.a $(BUILD)/include
	# Copy static headers from source
	cp -r include/* $(BUILD)/include/
	# Copy generated headers from cargo target directory (if they exist)
	# This fixes the missing assert.h issue
	if [ -d "$(CARGO_BUILD_DIR)/include" ]; then \
		cp -r $(CARGO_BUILD_DIR)/include/* $(BUILD)/include/; \
	fi

# 3. Compile OpenLibm
# Depends on 'headers' to ensure $(BUILD)/include is fully populated with assert.h etc.
$(BUILD)/openlibm/libopenlibm.a: $(BUILD)/include $(BUILD)/openlibm headers
	$(MAKE) AR=$(AR) CC="$(CC)" LD=$(LD) \
		CPPFLAGS="-fno-stack-protector -ffreestanding -I$(abspath $(BUILD)/include) $(CC_NOSTDINC_FLAGS)" \
		CFLAGS="-O3 -fPIC -fno-stack-protector -ffreestanding -I$(abspath $(BUILD)/include) $(CC_NOSTDINC_FLAGS)" \
		-C $(BUILD)/openlibm libopenlibm.a

# 4. Combine Libraries
$(BUILD)/libc.a: $(BUILD)/librelibc.a $(BUILD)/openlibm/libopenlibm.a
	echo "create $@" > $(BUILD)/libc.mri
	echo "addlib $(BUILD)/librelibc.a" >> $(BUILD)/libc.mri
	echo "addlib $(BUILD)/openlibm/libopenlibm.a" >> $(BUILD)/libc.mri
	echo "save" >> $(BUILD)/libc.mri
	echo "end" >> $(BUILD)/libc.mri
	$(AR) -M < $(BUILD)/libc.mri

$(BUILD)/libc.so: $(BUILD)/librelibc.a $(BUILD)/openlibm/libopenlibm.a
	$(CC) -nostdlib -shared -Wl,-soname,libc.so -o $@ \
		-Wl,--whole-archive $(BUILD)/librelibc.a $(BUILD)/openlibm/libopenlibm.a -Wl,--no-whole-archive \
		-lgcc

$(BUILD)/crt0.o: src/crt0/src/lib.rs
	mkdir -p $(BUILD)
	rustc --crate-type object --emit obj=$@ $< $(CARGO_FLAGS)

install: install-headers install-libs

install-headers: headers
	mkdir -p $(DESTDIR)/include
	cp -r $(BUILD)/include/* $(DESTDIR)/include/

install-libs: libs $(BUILD)/crt0.o
	mkdir -p $(DESTDIR)/lib
	cp $(BUILD)/libc.a $(DESTDIR)/lib/
	cp $(BUILD)/libc.so $(DESTDIR)/lib/
	cp $(BUILD)/crt0.o $(DESTDIR)/lib/

clean:
	cargo clean
	rm -rf $(BUILD)

test: all
	$(MAKE) -C tests all