# POSIX header spec: https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/sys_uio.h.html
#
# Split out to avoid including all of sys/uio.h in sys/socket.h.
#
# POSIX headers that require iovec:
# - sys/socket.h
# - sys/uio.h (where it should be defined)
#
# sys/types.h included for c_void and size_t
sys_includes = ["sys/types.h"]
include_guard = "_RELIBC_BITS_IOVEC_H"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true
