# POSIX header spec: https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/sys_types.h.html
#
# These types are split out to prevent importing all of sys/types.h into sys/statvfs.h.
#
# POSIX headers that require fsblkcnt_t and fsfilcnt_t:
# - sys/statvfs.h
# - sys/types.h (where they should be defined)
sys_includes = []
include_guard = "_RELIBC_BITS_SYS_STATVFS_H"
language = "C"
style = "type"
no_includes = true
cpp_compat = true
[export]
include = [
  "fsblkcnt_t",
  "fsfilcnt_t"
]
[enum]
prefix_with_name = true
