/* automatically generated by rust-bindgen */

pub extern "C" fn isalnum(arg1: libc::c_int) -> libc::c_int {
    unimplemented!();
}

pub extern "C" fn isalpha(arg1: libc::c_int) -> libc::c_int {
    unimplemented!();
}

pub extern "C" fn isascii(arg1: libc::c_int) -> libc::c_int {
    unimplemented!();
}

pub extern "C" fn iscntrl(arg1: libc::c_int) -> libc::c_int {
    unimplemented!();
}

pub extern "C" fn isdigit(arg1: libc::c_int) -> libc::c_int {
    unimplemented!();
}

pub extern "C" fn isgraph(arg1: libc::c_int) -> libc::c_int {
    unimplemented!();
}

pub extern "C" fn islower(arg1: libc::c_int) -> libc::c_int {
    unimplemented!();
}

pub extern "C" fn isprint(arg1: libc::c_int) -> libc::c_int {
    unimplemented!();
}

pub extern "C" fn ispunct(arg1: libc::c_int) -> libc::c_int {
    unimplemented!();
}

pub extern "C" fn isspace(arg1: libc::c_int) -> libc::c_int {
    unimplemented!();
}

pub extern "C" fn isupper(arg1: libc::c_int) -> libc::c_int {
    unimplemented!();
}

pub extern "C" fn isxdigit(arg1: libc::c_int) -> libc::c_int {
    unimplemented!();
}

pub extern "C" fn toascii(arg1: libc::c_int) -> libc::c_int {
    unimplemented!();
}

pub extern "C" fn tolower(arg1: libc::c_int) -> libc::c_int {
    unimplemented!();
}

pub extern "C" fn toupper(arg1: libc::c_int) -> libc::c_int {
    unimplemented!();
}
