sys_includes = ["stdint.h", "sys/types.h"]
include_guard = "_RELIBC_FENV_H"
language = "C"
style = "type"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true


[export]
item_types = ["constants", "functions", "typedefs", "structs"]
include = ["fexcept_t", "fenv_t"]

[defines]
"target_arch = aarch64" = "__aarch64__"
"target_arch = x86" = "__x86__"
"target_arch = x86_64" = "__x86_64__"