# POSIX header spec: https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/arpa_inet.h.html
#
# arpa/inet.h should define the following functions:
# - htonl
# - htons
# - ntohl
# - ntohs
#
# They are also meant to be available in netinet/in.h.
# Both arpa/inet.h and netinet/in.h say that they may include each other which creates a cycle.
# To break the cycle we include netinet/in.h in arpa/inet.h and split out the above functions.
#
# inttypes.h brings in uint16_t and uint32_t
# arpa/inet.h and netinet/in.h may include all of inttypes.h
sys_includes = ["inttypes.h"]
include_guard = "_RELIBC_BITS_ARPAINET_H"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true
