# POSIX header spec: https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/pthread.h.html
#
# Spec quotations relating to includes:
# - "The <pthread.h> header shall define the pthread_attr_t, pthread_barrier_t, pthread_barrierattr_t, pthread_cond_t, pthread_condattr_t, pthread_key_t, pthread_mutex_t, pthread_mutexattr_t, pthread_once_t, pthread_rwlock_t, pthread_rwlockattr_t, pthread_spinlock_t, and pthread_t types as described in <sys/types.h>."
# - "Inclusion of the <pthread.h> header shall make symbols defined in the headers <sched.h> and <time.h> visible."
#
# bits/pthread.h bring in the types from sys/types.h
# features.h needed for no return (Rust never type)
sys_includes = ["sched.h", "time.h", "bits/pthread.h", "features.h"]
include_guard = "_RELIBC_PTHREAD_H"
language = "C"
style = "tag"
no_includes = true
cpp_compat = true

[export.rename]
"timespec" = "struct timespec"
"sched_param" = "struct sched_param"

[enum]
prefix_with_name = true
