/* automatically generated by rust-bindgen */

pub extern "C" fn memccpy(arg1: *mut libc::c_void,
                   arg2: *const libc::c_void,
                   arg3: libc::c_int, arg4: usize)
     -> *mut libc::c_void {
    unimplemented!();
}

pub extern "C" fn memchr(arg1: *const libc::c_void,
                  arg2: libc::c_int, arg3: usize)
     -> *mut libc::c_void {
    unimplemented!();
}

pub extern "C" fn memcmp(arg1: *const libc::c_void,
                  arg2: *const libc::c_void, arg3: usize)
     -> libc::c_int {
    unimplemented!();
}

pub extern "C" fn memcpy(arg1: *mut libc::c_void,
                  arg2: *const libc::c_void, arg3: usize)
     -> *mut libc::c_void {
    unimplemented!();
}

pub extern "C" fn memmove(arg1: *mut libc::c_void,
                   arg2: *const libc::c_void, arg3: usize)
     -> *mut libc::c_void {
    unimplemented!();
}

pub extern "C" fn memset(arg1: *mut libc::c_void,
                  arg2: libc::c_int, arg3: usize)
     -> *mut libc::c_void {
    unimplemented!();
}

pub extern "C" fn strcat(arg1: *mut libc::c_char,
                  arg2: *const libc::c_char)
     -> *mut libc::c_char {
    unimplemented!();
}

pub extern "C" fn strchr(arg1: *const libc::c_char,
                  arg2: libc::c_int) -> *mut libc::c_char {
    unimplemented!();
}

pub extern "C" fn strcmp(arg1: *const libc::c_char,
                  arg2: *const libc::c_char)
     -> libc::c_int {
    unimplemented!();
}

pub extern "C" fn strcoll(arg1: *const libc::c_char,
                   arg2: *const libc::c_char)
     -> libc::c_int {
    unimplemented!();
}

pub extern "C" fn strcpy(arg1: *mut libc::c_char,
                  arg2: *const libc::c_char)
     -> *mut libc::c_char {
    unimplemented!();
}

pub extern "C" fn strcspn(arg1: *const libc::c_char,
                   arg2: *const libc::c_char)
     -> libc::c_ulong {
    unimplemented!();
}

pub extern "C" fn strdup(arg1: *const libc::c_char)
     -> *mut libc::c_char {
    unimplemented!();
}

pub extern "C" fn strerror(arg1: libc::c_int)
     -> *mut libc::c_char {
    unimplemented!();
}

pub extern "C" fn strlen(arg1: *const libc::c_char)
     -> libc::c_ulong {
    unimplemented!();
}

pub extern "C" fn strncat(arg1: *mut libc::c_char,
                   arg2: *const libc::c_char, arg3: usize)
     -> *mut libc::c_char {
    unimplemented!();
}

pub extern "C" fn strncmp(arg1: *const libc::c_char,
                   arg2: *const libc::c_char, arg3: usize)
     -> libc::c_int {
    unimplemented!();
}

pub extern "C" fn strncpy(arg1: *mut libc::c_char,
                   arg2: *const libc::c_char, arg3: usize)
     -> *mut libc::c_char {
    unimplemented!();
}

pub extern "C" fn strpbrk(arg1: *const libc::c_char,
                   arg2: *const libc::c_char)
     -> *mut libc::c_char {
    unimplemented!();
}

pub extern "C" fn strrchr(arg1: *const libc::c_char,
                   arg2: libc::c_int)
     -> *mut libc::c_char {
    unimplemented!();
}

pub extern "C" fn strspn(arg1: *const libc::c_char,
                  arg2: *const libc::c_char)
     -> libc::c_ulong {
    unimplemented!();
}

pub extern "C" fn strstr(arg1: *const libc::c_char,
                  arg2: *const libc::c_char)
     -> *mut libc::c_char {
    unimplemented!();
}

pub extern "C" fn strtok(arg1: *mut libc::c_char,
                  arg2: *const libc::c_char)
     -> *mut libc::c_char {
    unimplemented!();
}

pub extern "C" fn strtok_r(arg1: *mut libc::c_char,
                    arg2: *const libc::c_char,
                    arg3: *mut *mut libc::c_char)
     -> *mut libc::c_char {
    unimplemented!();
}

pub extern "C" fn strxfrm(arg1: *mut libc::c_char,
                   arg2: *const libc::c_char, arg3: usize)
     -> libc::c_ulong {
    unimplemented!();
}

