/* automatically generated by rust-bindgen */

#[no_mangle]
pub extern "C" fn memccpy(
    s1: *mut libc::c_void,
    s2: *const libc::c_void,
    c: libc::c_int,
    n: usize,
) -> *mut libc::c_void {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn memchr(
    s: *const libc::c_void,
    c: libc::c_int,
    n: usize,
) -> *mut libc::c_void {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn memcmp(
    s1: *const libc::c_void,
    s2: *const libc::c_void,
    n: usize,
) -> libc::c_int {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn memcpy(
    s1: *mut libc::c_void,
    s2: *const libc::c_void,
    n: usize,
) -> *mut libc::c_void {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn memmove(
    s1: *mut libc::c_void,
    s2: *const libc::c_void,
    n: usize,
) -> *mut libc::c_void {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn memset(
    s: *mut libc::c_void,
    c: libc::c_int,
    n: usize,
) -> *mut libc::c_void {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn strcat(s1: *mut libc::c_char, s2: *const libc::c_char) -> *mut libc::c_char {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn strchr(s: *const libc::c_char, c: libc::c_int) -> *mut libc::c_char {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn strcmp(s1: *const libc::c_char, s2: *const libc::c_char) -> libc::c_int {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn strcoll(s1: *const libc::c_char, s2: *const libc::c_char) -> libc::c_int {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn strcpy(s1: *mut libc::c_char, s2: *const libc::c_char) -> *mut libc::c_char {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn strcspn(s1: *const libc::c_char, s2: *const libc::c_char) -> libc::c_ulong {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn strdup(s1: *const libc::c_char) -> *mut libc::c_char {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn strerror(errnum: libc::c_int) -> *mut libc::c_char {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn strlen(s: *const libc::c_char) -> libc::c_ulong {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn strncat(
    s1: *mut libc::c_char,
    s2: *const libc::c_char,
    n: usize,
) -> *mut libc::c_char {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn strncmp(
    s1: *const libc::c_char,
    s2: *const libc::c_char,
    n: usize,
) -> libc::c_int {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn strncpy(
    s1: *mut libc::c_char,
    s2: *const libc::c_char,
    n: usize,
) -> *mut libc::c_char {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn strpbrk(
    s1: *const libc::c_char,
    s2: *const libc::c_char,
) -> *mut libc::c_char {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn strrchr(s: *const libc::c_char, c: libc::c_int) -> *mut libc::c_char {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn strspn(s1: *const libc::c_char, s2: *const libc::c_char) -> libc::c_ulong {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn strstr(
    s1: *const libc::c_char,
    s2: *const libc::c_char,
) -> *mut libc::c_char {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn strtok(s1: *mut libc::c_char, s2: *const libc::c_char) -> *mut libc::c_char {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn strtok_r(
    s: *mut libc::c_char,
    sep: *const libc::c_char,
    lasts: *mut *mut libc::c_char,
) -> *mut libc::c_char {
    unimplemented!();
}

#[no_mangle]
pub extern "C" fn strxfrm(
    s1: *mut libc::c_char,
    s2: *const libc::c_char,
    n: usize,
) -> libc::c_ulong {
    unimplemented!();
}
