sys_includes = ["bits/signal.h", "stdint.h", "sys/types.h", "time.h", "bits/pthread.h"]
include_guard = "_RELIBC_SIGNAL_H"
trailer = "#include <bits/signal.h>"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[defines]
"target_os=linux" = "__linux__"
"target_os=redox" = "__redox__"
"target_arch = x86" = "__i386__"
"target_arch = x86_64" = "__x86_64__"
"target_arch = aarch64" = "__aarch64__"

[enum]
prefix_with_name = true

[export.rename]
"timespec" = "struct timespec"
"sigaction" = "struct sigaction"
