# POSIX header spec: https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/sched.h.html
#
# Spec quotations relating to includes:
# - "The <sched.h> header shall define the pid_t type as described in <sys/types.h>."
# - "The <sched.h> header shall define the time_t type as described in <sys/types.h>."
# - "The <sched.h> header shall define the timespec structure as described in <time.h>."
# - "Inclusion of the <sched.h> header may make visible all symbols from the <time.h> header."
#
# bits/timespec.h brings in time_t
sys_includes = []
include_guard = "_RELIBC_SCHED_H"
after_includes = """
#include <bits/pid-t.h>    // for pid_t from sys/types
#include <bits/timespec.h> // for timespec from time.h
"""
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true

[export]
include = ["sched_param"]

[export.rename]
"timespec" = "struct timespec"
