# POSIX header spec: https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/sys_types.h.html
#
# POSIX headers that require key_t:
# - sys/ipc.h
# - sys/types (where it should be defined)
include_guard = "_RELIBC_BITS_KEY_T_H"
language = "C"
no_includes = true
cpp_compat = true
[export]
include = ["key_t"]
[enum]
prefix_with_name = true
