# POSIX header spec: https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/dirent.h.html
#
# Spec quotations relating to includes:
# - "The <dirent.h> header shall define the ino_t, reclen_t, size_t, and ssize_t types as described in <sys/types.h>."
sys_includes = ["sys/types.h"]
include_guard = "_RELIBC_DIRENT_H"
language = "C"
style = "Both"
after_includes = """

// Shamelessly stolen from musl
// Macros to convert between struct dirent and struct stat types.
#define IFTODT(x) ((x)>>12 & 017)
#define DTTOIF(x) ((x)<<12)
"""
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true
