# POSIX header spec: https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/inttypes.h.html
#
# Spec quotations relating to includes:
# - "The <inttypes.h> header shall include the <stdint.h> header."
# - "wchar_t As described in <stddef.h>."
#
# wchar.h brings in both stdint.h and stddef.h
sys_includes = ["wchar.h"]
include_guard = "_RELIBC_INTTYPES_H"
language = "C"
style = "Type"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true
