# Open flags are defined by fcntl.h: https://pubs.opengroup.org/onlinepubs/007904975/basedefs/fcntl.h.html
# And must be included in stdlib.h: https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/stdlib.h.html
include_guard = "_RELIBC_BITS_OPEN_FLAGS_H"
language = "C"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true
