# POSIX header spec: https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/sys_socket.h.html
#
# This type is split out to prevent importing all of sys/socket.h into other headers.
#
# POSIX headers that require sa_family_t:
# - netinet/in.h
# - sys/socket.h (where it should be defined)
# - sys/un.h
include_guard = "_RELIBC_BITS_SA_FAMILY_T_H"
language = "C"
no_includes = true
cpp_compat = true
[export]
include = ["sa_family_t"]
[enum]
prefix_with_name = true
