# POSIX header spec: https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/time.h.html
#
# Spec quotations relating to includes:
# - "The <time.h> header shall define the clock_t, size_t, time_t, types as described in <sys/types.h>."
# - "The <time.h> header shall define the clockid_t and timer_t types as described in <sys/types.h>."
# - "The <time.h> header shall define the locale_t type as described in <locale.h>."
# - "The <time.h> header shall define the pid_t type as described in <sys/types.h>."
# - "The tag sigevent shall be declared as naming an incomplete structure type, the contents of which are described in the <signal.h> header."
# - "NULL As described in <stddef.h>."
# - "Inclusion of the <time.h> header may make visible all symbols from the <signal.h> header."
#
# features.h included for deprecated annotations
sys_includes = ["sys/types.h", "stddef.h", "features.h"]
include_guard = "_RELIBC_TIME_H"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true
after_includes = """
#include <bits/timespec.h> // for timespec
#include <bits/locale-t.h> // for locale_t from locale.h

struct sigevent;
"""

[enum]
prefix_with_name = true

[export.rename]
"timespec" = "struct timespec"
"sigevent" = "struct sigevent"
