sys_includes = ["sys/ioctl.h", "termios.h"]
include_guard = "_RELIBC_PTY_H"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true

[export.rename]
"winsize" = "struct winsize"
"termios" = "struct termios"