# POSIX header spec: https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/sys_types.h.html
#
# These types are split out to prevent importing all of sys/types.h into other headers.
#
# POSIX headers that require them:
# - aio.h (pthread_attr_t only)
# - pthread.h (all of them)
# - signal.h (pthread_t and pthread_attr_t only)
# - sys/types.h (where they should be defined)
include_guard = "_RELIBC_BITS_PTHREAD_H"
language = "C"
style = "type"
no_includes = true
cpp_compat = true
after_includes = """
#include <bits/pthread-t.h>     // for pthread_t from sys/types.h
#include <bits/pthreadattr-t.h> // for pthread_attr_t from sys/types.h
#include <bits/pthreadonce-t.h> // for pthread_once_t from sys/types.h
#include <bits/threads.h>       // for pthread_{key|mutex|cond}_t from sys/types.h

"""

[export]
include = [
  "pthread_rwlockattr_t",
  "pthread_rwlock_t",
  "pthread_barrier_t",
  "pthread_barrierattr_t",
  "pthread_mutexattr_t",
  "pthread_condattr_t",
  "pthread_spinlock_t",
]

[enum]
prefix_with_name = true
