# POSIX header spec: https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/poll.h.html
#
# Spec quotations relating to includes:
# - "The <poll.h> header shall define the sigset_t type as described in <signal.h>."
# - "The <poll.h> header shall define the timespec structure as described in <time.h>."
# - "Inclusion of the <poll.h> header may make visible all symbols from the headers <signal.h> and <time.h>."
#
# bits/timespec.h brings in sys/types.h (TODO: refactor bits/timespec.h and sys/types.h)
sys_includes = []
include_guard = "_RELIBC_POLL_H"
after_includes = """
#include <bits/sigset-t.h> // for sigset_t from signal.h
#include <bits/timespec.h> // for timespec from time.h
"""
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true

[export.rename]
"timespec" = "struct timespec"
