# POSIX header spec: https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/cpio.h.html
#
# There are no spec quotations relating to includes
sys_includes = []
include_guard = "_RELIBC_CPIO_H"
# cbindgen still can't handle exporting CStr
after_includes = """
#define MAGIC "070707"
"""
language = "C"
style = "Type"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true
