# POSIX header spec: https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/sys_uio.h.html
#
# Spec quotations relating to includes:
# - "The <sys/uio.h> header shall define the ssize_t and size_t types as described in <sys/types.h>."
#
# bits/iovec.h brings in sys/types.h
sys_includes = ["bits/iovec.h"]
include_guard = "_SYS_UIO_H"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true

[export.rename]
"iovec" = "struct iovec"
