[package]
name = "libm"
version = "0.1.0"
authors = ["Darley Barreto <darleybarreto@gmail.com>"]
edition = "2021"

[lib]
path = "lib.rs"
crate-type = ["staticlib"]

[profile.release]
panic = "abort"
opt-level = 3