sys_includes = ["features.h", "stddef.h"]
include_guard = "_RELIBC_MALLOC_H"
trailer = "#include <bits/malloc.h>"
language = "C"
style = "Type"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true
