sys_includes = ["stdint.h", "stdio.h"]
after_includes = """
#include <bits/size-t.h> // for size_t from sys/types.h
"""
include_guard = "_RELIBC_SHADOW_H"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true

[export]
include = ["group"]
