include_guard = "_SYS_IOCTL_H"
language = "C"
style = "Tag"
trailer = "#include <bits/sys/ioctl.h>"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true

[export]
include = ["sgttyb", "winsize"]
