# stddef.h brings in size_t
# bits/useconds-t.h brings in features.h for deprecated annotation
sys_includes = ["stddef.h"]
after_includes = """
#include <bits/clock-t.h>
#include <bits/clockid-t.h>
#include <bits/dev-t.h>
#include <bits/gid-t.h>
#include <bits/id-t.h>
#include <bits/ino-t.h>
#include <bits/key-t.h>
#include <bits/mode-t.h>
#include <bits/nlink-t.h>
#include <bits/off-t.h>
#include <bits/pid-t.h>
#include <bits/reclen-t.h>
#include <bits/ssize-t.h>
#include <bits/suseconds-t.h>
#include <bits/sys/stat.h>    // for blkcnt_t and blksize_t
#include <bits/sys/statvfs.h> // for fsblkcnt_t and fsfilcnt_t
#include <bits/time-t.h>
#include <bits/timer-t.h>
#include <bits/uid-t.h>
#include <bits/useconds-t.h>  // from older POSIX
"""
include_guard = "_RELIBC_SYS_TYPES_INTERNAL_H"
language = "C"
no_includes = true

[export]
include = [
  "u_char",
  "uchar",
  "u_short",
  "ushort",
  "u_int",
  "uint",
  "u_long",
  "ulong",
  "quad_t",
  "u_quad_t",
  "caddr_t"
]
