# stddef.h brings in size_t and NULL
# fcntl.h brings in sys/stat.h bringing in off_t, gid_t and uid_t
# fcntl.h brings in pid_t
# bits/useconds-t.h brings in features.h (for deprecated annotations)
sys_includes = ["stddef.h", "stdint.h", "fcntl.h"]
include_guard = "_RELIBC_UNISTD_H"
after_includes = """
#include <bits/ssize-t.h>    // for ssize_t from sys/types.h
// for deprecated ualarm and usleep
#include <bits/useconds-t.h> // for useconds_t from sys/types.h

#define _POSIX_VERSION 200809L
#define _POSIX_BARRIERS 202405L
#define _POSIX_MONOTONIC_CLOCK 200112L
#define _POSIX_REALTIME_SIGNALS 202405L
#define _POSIX_SEMAPHORES 200112L
#define _POSIX_SHELL 1
#define _POSIX_SHARED_MEMORY_OBJECTS 200112L
#define _POSIX_THREADS 202405L
#define _POSIX_THREAD_ATTR_STACKADDR 202405L
#define _POSIX_THREAD_ATTR_STACKSIZE 202405L
#define _POSIX_TIMEOUTS 202405L
#define _POSIX_TIMERS 202405L
#define _XOPEN_SHM 1
#define _XOPEN_VERSION 700L
"""
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true
