# POSIX header spec: https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/unistd.h.html
#
# Spec quotations relating to includes:
# - "The <unistd.h> header shall define NULL as described in <stddef.h>."
# - "The <unistd.h> header shall define the symbolic constants O_CLOEXEC and O_CLOFORK as described in <fcntl.h>."
# - "The <unistd.h> header shall define SEEK_CUR, SEEK_END, and SEEK_SET as described in <stdio.h>."
# - "The <unistd.h> header shall define the size_t, ssize_t, uid_t, gid_t, off_t, and pid_t types as described in <sys/types.h>."
# - "The <unistd.h> header shall define the intptr_t type as described in <stdint.h>."
# - "Inclusion of the <unistd.h> header may make visible all symbols from the headers <fcntl.h>, <stddef.h>, <stdint.h>, and <stdio.h>."
#
# Note that unistd.h may include fcntl.h and fcntl.h may include unistd.h thus creating a cycle.
# Relibc decides that unistd.h will include fcntl.h and fcntl.h will not include unistd.h.
#
# stddef.h brings in size_t and NULL
# fcntl.h brings in bits/fcntl.h bringing in SEEK_CUR, SEEK_END and SEEK_SET
# fcntl.h brings in sys/stat.h bringing in off_t, gid_t and uid_t
# fcntl.h brings in pid_t
# bits/useconds-t.h brings in features.h (for deprecated annotations)
sys_includes = ["stddef.h", "stdint.h", "fcntl.h"]
include_guard = "_RELIBC_UNISTD_H"
after_includes = """
#include <bits/ssize-t.h>    // for ssize_t from sys/types.h
// for deprecated ualarm and usleep
#include <bits/useconds-t.h> // for useconds_t from sys/types.h

#define _POSIX_VERSION 200809L
#define _POSIX_BARRIERS 202405L
#define _POSIX_MONOTONIC_CLOCK 200112L
#define _POSIX_REALTIME_SIGNALS 202405L
#define _POSIX_SEMAPHORES 200112L
#define _POSIX_SHELL 1
#define _POSIX_SHARED_MEMORY_OBJECTS 200112L
#define _POSIX_THREADS 202405L
#define _POSIX_THREAD_ATTR_STACKADDR 202405L
#define _POSIX_THREAD_ATTR_STACKSIZE 202405L
#define _POSIX_TIMEOUTS 202405L
#define _POSIX_TIMERS 202405L
#define _XOPEN_SHM 1
#define _XOPEN_VERSION 700L
"""
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true
